name: Build WebApp APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Capacitor
        run: npm install -g @capacitor/cli

      - name: Create Capacitor Project
        run: |
          npx cap init MyGameApp com.example.game
          mkdir -p www
          cp -r * www/ || true

      - name: Add Android platform
        run: npx cap add android

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
